### ISSUE TITLE
Release v0.1.2 with commit e7887fc

### ISSUE THREAD

**Issue by paulmedynski** [paulmillr/native-notifier#7]
Can you release a new version of native-notifier with commit e7887fc's changes in it?  This should get picked up by loggy, and thus brunch, and would address brunch/brunch#1831.

**Comment by paulmillr** [comment]
Released.

**Comment by juan-manuel-alberro** [comment]
@paulmedynski I think the latest release broke the package

```bash
const loadE = moduleName => require(moduleName).on('error', () => {});
                            ^TypeError: require(...).on is not a function
```

**Comment by replicat0r** [comment]
i am also expericing this exact error, and i have been pulling my hair out to figure out if there was something wrong on my end.
